apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: multi-k8s-ml-tls
spec:
  secretName: multi-k8s-ml
  issuerRef: 
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: multi-k8s.ml
  dnsNames:
    - multi-k8s.ml
    - www.multi-k8s.ml
