apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-service-client
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  tls: 
    - hosts :
        - multi-k8s.ml
        - www.multi-k8s.ml
      secretName:  multi-k8s-ml
  rules:
    - host: multi-k8s.ml  
      http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                serviceName: client-cluster-ip-service
                servicePort: 3000
    - host: www.multi-k8s.ml  
      http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                serviceName: client-cluster-ip-service
                servicePort: 3000